import type { UnitConfig, OverloadPhase } from '@/types';
import { HEAT_CRITICAL_PER_TURN, HEAT_CRITICAL_DAMAGE_BONUS, HEAT_CRITICAL_HEAT_PENALTY } from '@/data/constants';
import { getOverloadPhase } from '@/systems/StatEngine';
import { eventBus } from '@/utils/EventBus';

export interface OverloadResult {
  unitId: string;
  phase: OverloadPhase;
  exploded: boolean;
  aoeDamage: number;   // damage dealt to adjacent units (both sides)
}

export const HeatManager = {
  // Add heat to a unit (from ability use, damage taken, etc.)
  addHeat(unit: UnitConfig, amount: number): OverloadPhase {
    unit.stats.heat = Math.min(unit.stats.heat + amount, unit.stats.thresh);
    const phase = getOverloadPhase(unit);
    eventBus.emit('heat:changed', { unitId: unit.id, heat: unit.stats.heat, phase });
    return phase;
  },

  // Remove heat (repair, cooling module, etc.)
  removeHeat(unit: UnitConfig, amount: number): void {
    unit.stats.heat = Math.max(0, unit.stats.heat - amount);
    eventBus.emit('heat:changed', {
      unitId: unit.id,
      heat: unit.stats.heat,
      phase: getOverloadPhase(unit),
    });
  },

  // Full heat reset (repair station)
  resetHeat(unit: UnitConfig): void {
    unit.stats.heat = 0;
    eventBus.emit('heat:changed', { unitId: unit.id, heat: 0, phase: 'safe' });
  },

  // Per-turn heat processing during battle
  processTurnHeat(unit: UnitConfig): OverloadResult {
    const phase = getOverloadPhase(unit);

    // Critical and meltdown phases: auto heat gain per turn
    if (phase === 'critical' || phase === 'meltdown') {
      const heatGain = phase === 'meltdown' ? HEAT_CRITICAL_PER_TURN * 2 : HEAT_CRITICAL_PER_TURN;
      unit.stats.heat = Math.min(
        unit.stats.heat + heatGain,
        unit.stats.thresh
      );
    }

    // Check for explosion (heat at or above threshold)
    const finalPhase = getOverloadPhase(unit);
    const exploded = unit.stats.heat >= unit.stats.thresh;

    let aoeDamage = 0;
    if (exploded) {
      // Explosion damage = 40% of unit's max HP
      aoeDamage = Math.round(unit.stats.maxHp * 0.4);
      unit.alive = false;
      unit.stats.hp = 0;
      eventBus.emit('heat:meltdown', { unitId: unit.id, damage: aoeDamage });
    }

    return { unitId: unit.id, phase: finalPhase, exploded, aoeDamage };
  },

  // Get damage multiplier for abilities based on heat phase
  getAbilityDamageMultiplier(unit: UnitConfig): number {
    const phase = getOverloadPhase(unit);
    if (phase === 'critical') return 1 + HEAT_CRITICAL_DAMAGE_BONUS; // +50%
    return 1;
  },

  // Get extra heat generated by abilities in critical phase
  getAbilityHeatMultiplier(unit: UnitConfig): number {
    const phase = getOverloadPhase(unit);
    if (phase === 'critical') return 1 + HEAT_CRITICAL_HEAT_PENALTY; // +40%
    return 1;
  },

  // Check if ability is disabled in warning phase
  isAbilityDisabled(unit: UnitConfig, isStrong: boolean): boolean {
    if (!isStrong) return false;
    const phase = getOverloadPhase(unit);
    return phase === 'warning'; // Strong abilities disabled in warning
  },
};
